# Generated by Django 4.0.4 on 2022-11-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['score', 'nickname']},
        ),
        migrations.AddField(
            model_name='guest',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
